theme: jekyll-theme-cayman

title: Human Resource Machine PL
description: Project site for iBug/HRM
author: iBug
show_downloads: true

github:
  zip_url: https://github.com/iBug/HRM/archive/master.zip
  tar_url: https://github.com/iBug/HRM/archive/master.tar.gz

plugins:
  - jekyll-redirect-from
